-- 코드를 입력하세요

WITH BOOKWITHSALE AS(
    SELECT A.AUTHOR_ID , A.CATEGORY, A.PRICE*B.SALES AS TOTAL_SALES
    FROM BOOK A JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE TO_CHAR(B.SALES_DATE,'YYYY')='2022' AND TO_CHAR(B.SALES_DATE,'MM')='01'
)

SELECT A.AUTHOR_ID,A.AUTHOR_NAME , B.CATEGORY, SUM(B.TOTAL_SALES) AS TOTAL_SALES
FROM AUTHOR A JOIN BOOKWITHSALE B
ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY
ORDER BY A.AUTHOR_ID,B.CATEGORY DESC;