-- 코드를 입력하세요

WITH MILK AS(
SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME='Milk')
,YOGURT AS(
SELECT CART_ID FROM CART_PRODUCTS
WHERE NAME='Yogurt')

SELECT MILK.CART_ID FROM
MILK JOIN YOGURT ON MILK.CART_ID = YOGURT.CART_ID
ORDER BY MILK.CART_ID;