-- 코드를 입력하세요
SELECT ANIMAL_ID,NAME FROM (
SELECT A.ANIMAL_ID,A.NAME, ROUND(B.DATETIME-A.DATETIME) AS 보호기간
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY 보호기간 DESC)
WHERE ROWNUM<=2;