-- 코드를 입력하세요
WITH FILTER_CAR_TYPE AS(
SELECT CAR_ID,CAR_TYPE,DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE IN ('세단','SUV')),

FILTER_AVAILABLE AS(
SELECT A.CAR_ID,B.CAR_TYPE,DAILY_FEE,A.START_DATE,A.END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN FILTER_CAR_TYPE B 
ON A.CAR_ID = B.CAR_ID
WHERE TO_CHAR(A.START_DATE,'YYYY-MM-DD')<='2022-11-30' AND
TO_CHAR(A.END_DATE,'YYYY-MM-DD')>='2022-11-01'),

DISCOUNT_RATE AS(
SELECT CAR_TYPE,DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
WHERE DURATION_TYPE LIKE '30%' AND CAR_TYPE IN ('세단','SUV')
)

SELECT C.CAR_ID,C.CAR_TYPE,C.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100 AS FEE FROM CAR_RENTAL_COMPANY_CAR C JOIN DISCOUNT_RATE B
ON C.CAR_TYPE = B.CAR_TYPE
WHERE NOT EXISTS ( SELECT CAR_ID FROM FILTER_AVAILABLE WHERE C.CAR_ID = CAR_ID )
AND C.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100<2000000 AND C.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100 >=500000
ORDER BY FEE DESC, C.CAR_TYPE,C.CAR_ID DESC