-- 코드를 입력하세요
WITH USERID AS(
SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(WRITER_ID)>2)

SELECT A.USER_ID,A.NICKNAME,
    A.CITY||' '||A.STREET_ADDRESS1||' '||A.STREET_ADDRESS2 AS "전체주소",
    SUBSTR(A.TLNO,0,3)||'-'||SUBSTR(A.TLNO,4,4)||'-'||SUBSTR(A.TLNO,8) AS "전화번호"
FROM USED_GOODS_USER A JOIN USERID B ON
A.USER_ID =B.WRITER_ID
ORDER BY A.USER_ID DESC