-- 코드를 입력하세요
SELECT A.ANIMAL_ID,A.ANIMAL_TYPE, A.NAME 
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE REGEXP_LIKE(A.SEX_UPON_INTAKE,'Intact') AND
REGEXP_LIKE(B.SEX_UPON_OUTCOME,'Spayed|Neutered')
ORDER BY A.ANIMAL_ID;