-- 코드를 입력하세요

SELECT 
TO_CHAR(B.SALES_DATE,'YYYY') AS YEAR,
TO_CHAR(B.SALES_DATE,'FMMM') AS MONTH,
A.GENDER AS GENDER ,COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A JOIN ONLINE_SALE B 
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY TO_CHAR(B.SALES_DATE,'FMMM'),TO_CHAR(B.SALES_DATE,'YYYY'),A.GENDER
ORDER BY TO_NUMBER(YEAR),TO_NUMBER(MONTH),TO_NUMBER(GENDER);