SELECT 
EXTRACT(YEAR FROM A.SALES_DATE) AS YEAR
, EXTRACT(MONTH FROM A.SALES_DATE) AS MONTH
, COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS
, ROUND(COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO  WHERE EXTRACT(YEAR FROM JOINED) = '2021'),1) AS PUCHASED_RATIO
FROM ONLINE_SALE A JOIN USER_INFO B ON B.USER_ID = A.USER_ID
WHERE EXTRACT(YEAR FROM B.JOINED) = '2021'
GROUP BY EXTRACT(MONTH FROM A.SALES_DATE),EXTRACT(YEAR FROM A.SALES_DATE)
ORDER BY YEAR,MONTH 