-- 코드를 입력하세요
WITH B AS (
    SELECT CAR_ID,CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE ='세단'
)

SELECT 
DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN B ON
A.CAR_ID = B.CAR_ID
WHERE 
EXTRACT(MONTH FROM A.START_DATE)=10
ORDER BY A.CAR_ID DESC